---
title: "eeeefff / expedition through it infrastructure"
output:
  html_document:
    df_print: paged
---

```{r prelude, include=FALSE}
source("prelude.R")
```

## list of data centers in moscow (winter 2016)
```{r load cods, echo=FALSE, rows.print=30}
cods <- fromJSON("./data/moscow_cods_with_coords.json", flatten=TRUE)
cods <- subset(cods, !is.na(coords.latitude))

cod_coords <- cods[, 6:7]
cod_coords$count <- 1
cod_coords <- rename(cod_coords, c("coords.latitude"="lat", "coords.longitude"="lon"))
cod_coords <- subset(cod_coords, !is.na(lat))

cods
```

```{r load moscow map, include=FALSE}
# 
# load moscow map
# 
# moscow coords: c(lon = 37.618423, lat = 55.751244)
moscow_map =  get_map(location = c(lon = 37.618423, lat = 55.751244), 
                      zoom = 10, 
                      scale = 1,
                      force = TRUE,
                      source="google")
```

## Data centers on map
```{r render cods on map, echo=FALSE, fig.height=10, fig.width=10, warning=FALSE}
ggmap(moscow_map,
      darken = c(0.5, "cyan"),
      extent = "device") + 
  # data center points
  geom_point(data = cods,
             aes(x = coords.longitude, y = coords.latitude, colour = "white"),
             size = 8,
             alpha = 0.8,
             colour = "white") +
  # data denters' names
  # geom_text_repel(data=cods, 
  #                 aes(x = coords.longitude, y = coords.latitude, label = name, color="red"), 
  #                 size=5,
  #                 alpha = .7) +
  scale_size_area() +
  labs(y = NULL, x = NULL) +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none")
```

